/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateStation } from '../models';
// @ts-ignore
import type { CreateStation201Response } from '../models';
// @ts-ignore
import type { DeleteStation200Response } from '../models';
// @ts-ignore
import type { GetAllStationsAdmin200Response } from '../models';
// @ts-ignore
import type { GetStationAdmin200Response } from '../models';
// @ts-ignore
import type { SimpleError } from '../models';
// @ts-ignore
import type { UpdateStation } from '../models';
// @ts-ignore
import type { UpdateStation200Response } from '../models';
/**
 * AdminStationApi - axios parameter creator
 * @export
 */
export const AdminStationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 관리자 전용. 새로운 대여소를 추가합니다.
         * @summary 대여소 추가
         * @param {CreateStation} [createStation] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createStation: async (createStation?: CreateStation, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/admin/stations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createStation, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 관리자 전용. 대여소를 삭제합니다
         * @summary 대여소 삭제
         * @param {string} stationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteStation: async (stationId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'stationId' is not null or undefined
            assertParamExists('deleteStation', 'stationId', stationId)
            const localVarPath = `/admin/stations/{stationId}`
                .replace(`{${"stationId"}}`, encodeURIComponent(String(stationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 관리자 전용. 전체 정류장 목록을 조회합니다. 검색 및 페이지네이션을 지원합니다.
         * @summary 대여소 목록 조회
         * @param {number} [page] 페이지 번호
         * @param {number} [limit] 페이지당 항목 수
         * @param {string} [search] 대여소 이름
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllStationsAdmin: async (page?: number, limit?: number, search?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/admin/stations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 관리자 전용. 특정 대여소의 상세 정보를 조회합니다
         * @summary 대여소 상세 조회
         * @param {string} stationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStationAdmin: async (stationId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'stationId' is not null or undefined
            assertParamExists('getStationAdmin', 'stationId', stationId)
            const localVarPath = `/admin/stations/{stationId}`
                .replace(`{${"stationId"}}`, encodeURIComponent(String(stationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 관리자 전용. 대여소 정보를 수정합니다.
         * @summary 대여소 정보 수정
         * @param {string} stationId 대여소 ID
         * @param {UpdateStation} [updateStation] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateStation: async (stationId: string, updateStation?: UpdateStation, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'stationId' is not null or undefined
            assertParamExists('updateStation', 'stationId', stationId)
            const localVarPath = `/admin/stations/{stationId}`
                .replace(`{${"stationId"}}`, encodeURIComponent(String(stationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateStation, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminStationApi - functional programming interface
 * @export
 */
export const AdminStationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminStationApiAxiosParamCreator(configuration)
    return {
        /**
         * 관리자 전용. 새로운 대여소를 추가합니다.
         * @summary 대여소 추가
         * @param {CreateStation} [createStation] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createStation(createStation?: CreateStation, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateStation201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createStation(createStation, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminStationApi.createStation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 관리자 전용. 대여소를 삭제합니다
         * @summary 대여소 삭제
         * @param {string} stationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteStation(stationId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeleteStation200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteStation(stationId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminStationApi.deleteStation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 관리자 전용. 전체 정류장 목록을 조회합니다. 검색 및 페이지네이션을 지원합니다.
         * @summary 대여소 목록 조회
         * @param {number} [page] 페이지 번호
         * @param {number} [limit] 페이지당 항목 수
         * @param {string} [search] 대여소 이름
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllStationsAdmin(page?: number, limit?: number, search?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetAllStationsAdmin200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllStationsAdmin(page, limit, search, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminStationApi.getAllStationsAdmin']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 관리자 전용. 특정 대여소의 상세 정보를 조회합니다
         * @summary 대여소 상세 조회
         * @param {string} stationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStationAdmin(stationId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetStationAdmin200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStationAdmin(stationId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminStationApi.getStationAdmin']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 관리자 전용. 대여소 정보를 수정합니다.
         * @summary 대여소 정보 수정
         * @param {string} stationId 대여소 ID
         * @param {UpdateStation} [updateStation] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateStation(stationId: string, updateStation?: UpdateStation, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UpdateStation200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateStation(stationId, updateStation, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminStationApi.updateStation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminStationApi - factory interface
 * @export
 */
export const AdminStationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminStationApiFp(configuration)
    return {
        /**
         * 관리자 전용. 새로운 대여소를 추가합니다.
         * @summary 대여소 추가
         * @param {CreateStation} [createStation] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createStation(createStation?: CreateStation, options?: RawAxiosRequestConfig): AxiosPromise<CreateStation201Response> {
            return localVarFp.createStation(createStation, options).then((request) => request(axios, basePath));
        },
        /**
         * 관리자 전용. 대여소를 삭제합니다
         * @summary 대여소 삭제
         * @param {string} stationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteStation(stationId: string, options?: RawAxiosRequestConfig): AxiosPromise<DeleteStation200Response> {
            return localVarFp.deleteStation(stationId, options).then((request) => request(axios, basePath));
        },
        /**
         * 관리자 전용. 전체 정류장 목록을 조회합니다. 검색 및 페이지네이션을 지원합니다.
         * @summary 대여소 목록 조회
         * @param {number} [page] 페이지 번호
         * @param {number} [limit] 페이지당 항목 수
         * @param {string} [search] 대여소 이름
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllStationsAdmin(page?: number, limit?: number, search?: string, options?: RawAxiosRequestConfig): AxiosPromise<GetAllStationsAdmin200Response> {
            return localVarFp.getAllStationsAdmin(page, limit, search, options).then((request) => request(axios, basePath));
        },
        /**
         * 관리자 전용. 특정 대여소의 상세 정보를 조회합니다
         * @summary 대여소 상세 조회
         * @param {string} stationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStationAdmin(stationId: string, options?: RawAxiosRequestConfig): AxiosPromise<GetStationAdmin200Response> {
            return localVarFp.getStationAdmin(stationId, options).then((request) => request(axios, basePath));
        },
        /**
         * 관리자 전용. 대여소 정보를 수정합니다.
         * @summary 대여소 정보 수정
         * @param {string} stationId 대여소 ID
         * @param {UpdateStation} [updateStation] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateStation(stationId: string, updateStation?: UpdateStation, options?: RawAxiosRequestConfig): AxiosPromise<UpdateStation200Response> {
            return localVarFp.updateStation(stationId, updateStation, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminStationApi - object-oriented interface
 * @export
 * @class AdminStationApi
 * @extends {BaseAPI}
 */
export class AdminStationApi extends BaseAPI {
    /**
     * 관리자 전용. 새로운 대여소를 추가합니다.
     * @summary 대여소 추가
     * @param {CreateStation} [createStation] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminStationApi
     */
    public createStation(createStation?: CreateStation, options?: RawAxiosRequestConfig) {
        return AdminStationApiFp(this.configuration).createStation(createStation, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 관리자 전용. 대여소를 삭제합니다
     * @summary 대여소 삭제
     * @param {string} stationId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminStationApi
     */
    public deleteStation(stationId: string, options?: RawAxiosRequestConfig) {
        return AdminStationApiFp(this.configuration).deleteStation(stationId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 관리자 전용. 전체 정류장 목록을 조회합니다. 검색 및 페이지네이션을 지원합니다.
     * @summary 대여소 목록 조회
     * @param {number} [page] 페이지 번호
     * @param {number} [limit] 페이지당 항목 수
     * @param {string} [search] 대여소 이름
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminStationApi
     */
    public getAllStationsAdmin(page?: number, limit?: number, search?: string, options?: RawAxiosRequestConfig) {
        return AdminStationApiFp(this.configuration).getAllStationsAdmin(page, limit, search, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 관리자 전용. 특정 대여소의 상세 정보를 조회합니다
     * @summary 대여소 상세 조회
     * @param {string} stationId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminStationApi
     */
    public getStationAdmin(stationId: string, options?: RawAxiosRequestConfig) {
        return AdminStationApiFp(this.configuration).getStationAdmin(stationId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 관리자 전용. 대여소 정보를 수정합니다.
     * @summary 대여소 정보 수정
     * @param {string} stationId 대여소 ID
     * @param {UpdateStation} [updateStation] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminStationApi
     */
    public updateStation(stationId: string, updateStation?: UpdateStation, options?: RawAxiosRequestConfig) {
        return AdminStationApiFp(this.configuration).updateStation(stationId, updateStation, options).then((request) => request(this.axios, this.basePath));
    }
}

