/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { RecommendCourse } from '../models';
// @ts-ignore
import type { RecommendCourse200Response } from '../models';
/**
 * AiApi - axios parameter creator
 * @export
 */
export const AiApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 사용자의 자연어 요청을 분석하여 적합한 자전거 코스를 추천합니다. 난이도, 소요 시간, 거리, 칼로리 소모량, 주요 경유지 등을 포함합니다. 현재는 키워드 기반 모의 AI를 사용합니다.
         * @summary AI 코스 추천
         * @param {RecommendCourse} recommendCourse 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recommendCourse: async (recommendCourse: RecommendCourse, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'recommendCourse' is not null or undefined
            assertParamExists('recommendCourse', 'recommendCourse', recommendCourse)
            const localVarPath = `/ai/recommend-course`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(recommendCourse, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 사용자의 자연어 요청을 분석하여 적합한 자전거 코스를 추천합니다. 난이도, 소요 시간, 거리, 칼로리 소모량, 주요 경유지 등을 포함합니다. 현재는 키워드 기반 모의 AI를 사용합니다.
         * @summary AI 코스 추천
         * @param {RecommendCourse} recommendCourse 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recommendCourse_1: async (recommendCourse: RecommendCourse, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'recommendCourse' is not null or undefined
            assertParamExists('recommendCourse_1', 'recommendCourse', recommendCourse)
            const localVarPath = `/ai/recommend-course`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(recommendCourse, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AiApi - functional programming interface
 * @export
 */
export const AiApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AiApiAxiosParamCreator(configuration)
    return {
        /**
         * 사용자의 자연어 요청을 분석하여 적합한 자전거 코스를 추천합니다. 난이도, 소요 시간, 거리, 칼로리 소모량, 주요 경유지 등을 포함합니다. 현재는 키워드 기반 모의 AI를 사용합니다.
         * @summary AI 코스 추천
         * @param {RecommendCourse} recommendCourse 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recommendCourse(recommendCourse: RecommendCourse, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RecommendCourse200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recommendCourse(recommendCourse, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AiApi.recommendCourse']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 사용자의 자연어 요청을 분석하여 적합한 자전거 코스를 추천합니다. 난이도, 소요 시간, 거리, 칼로리 소모량, 주요 경유지 등을 포함합니다. 현재는 키워드 기반 모의 AI를 사용합니다.
         * @summary AI 코스 추천
         * @param {RecommendCourse} recommendCourse 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recommendCourse_1(recommendCourse: RecommendCourse, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RecommendCourse200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recommendCourse_1(recommendCourse, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AiApi.recommendCourse_1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AiApi - factory interface
 * @export
 */
export const AiApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AiApiFp(configuration)
    return {
        /**
         * 사용자의 자연어 요청을 분석하여 적합한 자전거 코스를 추천합니다. 난이도, 소요 시간, 거리, 칼로리 소모량, 주요 경유지 등을 포함합니다. 현재는 키워드 기반 모의 AI를 사용합니다.
         * @summary AI 코스 추천
         * @param {RecommendCourse} recommendCourse 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recommendCourse(recommendCourse: RecommendCourse, options?: RawAxiosRequestConfig): AxiosPromise<RecommendCourse200Response> {
            return localVarFp.recommendCourse(recommendCourse, options).then((request) => request(axios, basePath));
        },
        /**
         * 사용자의 자연어 요청을 분석하여 적합한 자전거 코스를 추천합니다. 난이도, 소요 시간, 거리, 칼로리 소모량, 주요 경유지 등을 포함합니다. 현재는 키워드 기반 모의 AI를 사용합니다.
         * @summary AI 코스 추천
         * @param {RecommendCourse} recommendCourse 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recommendCourse_1(recommendCourse: RecommendCourse, options?: RawAxiosRequestConfig): AxiosPromise<RecommendCourse200Response> {
            return localVarFp.recommendCourse_1(recommendCourse, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AiApi - object-oriented interface
 * @export
 * @class AiApi
 * @extends {BaseAPI}
 */
export class AiApi extends BaseAPI {
    /**
     * 사용자의 자연어 요청을 분석하여 적합한 자전거 코스를 추천합니다. 난이도, 소요 시간, 거리, 칼로리 소모량, 주요 경유지 등을 포함합니다. 현재는 키워드 기반 모의 AI를 사용합니다.
     * @summary AI 코스 추천
     * @param {RecommendCourse} recommendCourse 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AiApi
     */
    public recommendCourse(recommendCourse: RecommendCourse, options?: RawAxiosRequestConfig) {
        return AiApiFp(this.configuration).recommendCourse(recommendCourse, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 사용자의 자연어 요청을 분석하여 적합한 자전거 코스를 추천합니다. 난이도, 소요 시간, 거리, 칼로리 소모량, 주요 경유지 등을 포함합니다. 현재는 키워드 기반 모의 AI를 사용합니다.
     * @summary AI 코스 추천
     * @param {RecommendCourse} recommendCourse 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AiApi
     */
    public recommendCourse_1(recommendCourse: RecommendCourse, options?: RawAxiosRequestConfig) {
        return AiApiFp(this.configuration).recommendCourse_1(recommendCourse, options).then((request) => request(this.axios, this.basePath));
    }
}

