/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AiCourseGet200Response } from '../models';
// @ts-ignore
import type { RecommendCourse200Response } from '../models';
/**
 * AiApi - axios parameter creator
 * @export
 */
export const AiApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 출발지와 목적지의 위,경도가 주어지면 그 둘을 잇는 경로가 반환됩니다.
         * @summary 코스 경로 제공
         * @param {string} [start] 출발지 위,경도
         * @param {string} [end] 목적지 위,경도
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aiCourseGet: async (start?: string, end?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/ai/course`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (start !== undefined) {
                localVarQueryParameter['start'] = start;
            }

            if (end !== undefined) {
                localVarQueryParameter['end'] = end;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 사용자의 자연어 요청을 분석하여 적합한 자전거 코스를 추천합니다.
         * @summary AI 코스 추천
         * @param {string} [prompt] 사용자가 입력한 prompt (LLM이 사용)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recommendCourse: async (prompt?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/ai/LLMrequest-coords`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (prompt !== undefined) {
                localVarQueryParameter['prompt'] = prompt;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 사용자의 자연어 요청을 분석하여 적합한 자전거 코스를 추천합니다.
         * @summary AI 코스 추천
         * @param {string} [prompt] 사용자가 입력한 prompt (LLM이 사용)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recommendCourse_1: async (prompt?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/ai/LLMrequest-coords`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (prompt !== undefined) {
                localVarQueryParameter['prompt'] = prompt;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AiApi - functional programming interface
 * @export
 */
export const AiApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AiApiAxiosParamCreator(configuration)
    return {
        /**
         * 출발지와 목적지의 위,경도가 주어지면 그 둘을 잇는 경로가 반환됩니다.
         * @summary 코스 경로 제공
         * @param {string} [start] 출발지 위,경도
         * @param {string} [end] 목적지 위,경도
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async aiCourseGet(start?: string, end?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AiCourseGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.aiCourseGet(start, end, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AiApi.aiCourseGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 사용자의 자연어 요청을 분석하여 적합한 자전거 코스를 추천합니다.
         * @summary AI 코스 추천
         * @param {string} [prompt] 사용자가 입력한 prompt (LLM이 사용)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recommendCourse(prompt?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RecommendCourse200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recommendCourse(prompt, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AiApi.recommendCourse']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 사용자의 자연어 요청을 분석하여 적합한 자전거 코스를 추천합니다.
         * @summary AI 코스 추천
         * @param {string} [prompt] 사용자가 입력한 prompt (LLM이 사용)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recommendCourse_1(prompt?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RecommendCourse200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recommendCourse_1(prompt, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AiApi.recommendCourse_1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AiApi - factory interface
 * @export
 */
export const AiApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AiApiFp(configuration)
    return {
        /**
         * 출발지와 목적지의 위,경도가 주어지면 그 둘을 잇는 경로가 반환됩니다.
         * @summary 코스 경로 제공
         * @param {string} [start] 출발지 위,경도
         * @param {string} [end] 목적지 위,경도
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aiCourseGet(start?: string, end?: string, options?: RawAxiosRequestConfig): AxiosPromise<AiCourseGet200Response> {
            return localVarFp.aiCourseGet(start, end, options).then((request) => request(axios, basePath));
        },
        /**
         * 사용자의 자연어 요청을 분석하여 적합한 자전거 코스를 추천합니다.
         * @summary AI 코스 추천
         * @param {string} [prompt] 사용자가 입력한 prompt (LLM이 사용)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recommendCourse(prompt?: string, options?: RawAxiosRequestConfig): AxiosPromise<RecommendCourse200Response> {
            return localVarFp.recommendCourse(prompt, options).then((request) => request(axios, basePath));
        },
        /**
         * 사용자의 자연어 요청을 분석하여 적합한 자전거 코스를 추천합니다.
         * @summary AI 코스 추천
         * @param {string} [prompt] 사용자가 입력한 prompt (LLM이 사용)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recommendCourse_1(prompt?: string, options?: RawAxiosRequestConfig): AxiosPromise<RecommendCourse200Response> {
            return localVarFp.recommendCourse_1(prompt, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AiApi - object-oriented interface
 * @export
 * @class AiApi
 * @extends {BaseAPI}
 */
export class AiApi extends BaseAPI {
    /**
     * 출발지와 목적지의 위,경도가 주어지면 그 둘을 잇는 경로가 반환됩니다.
     * @summary 코스 경로 제공
     * @param {string} [start] 출발지 위,경도
     * @param {string} [end] 목적지 위,경도
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AiApi
     */
    public aiCourseGet(start?: string, end?: string, options?: RawAxiosRequestConfig) {
        return AiApiFp(this.configuration).aiCourseGet(start, end, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 사용자의 자연어 요청을 분석하여 적합한 자전거 코스를 추천합니다.
     * @summary AI 코스 추천
     * @param {string} [prompt] 사용자가 입력한 prompt (LLM이 사용)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AiApi
     */
    public recommendCourse(prompt?: string, options?: RawAxiosRequestConfig) {
        return AiApiFp(this.configuration).recommendCourse(prompt, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 사용자의 자연어 요청을 분석하여 적합한 자전거 코스를 추천합니다.
     * @summary AI 코스 추천
     * @param {string} [prompt] 사용자가 입력한 prompt (LLM이 사용)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AiApi
     */
    public recommendCourse_1(prompt?: string, options?: RawAxiosRequestConfig) {
        return AiApiFp(this.configuration).recommendCourse_1(prompt, options).then((request) => request(this.axios, this.basePath));
    }
}

