/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CheckEmailAvailability200Response } from '../models';
// @ts-ignore
import type { Login } from '../models';
// @ts-ignore
import type { LoginUser200Response } from '../models';
// @ts-ignore
import type { Signup } from '../models';
// @ts-ignore
import type { SignupUser201Response } from '../models';
/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 회원가입 시 이메일 중복 여부를 확인합니다. 사용 가능한 이메일인 경우 available: true를 반환합니다.
         * @summary 이메일 중복 확인
         * @param {string} email 확인할 이메일 주소
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkEmailAvailability: async (email: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'email' is not null or undefined
            assertParamExists('checkEmailAvailability', 'email', email)
            const localVarPath = `/auth/check-email`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (email !== undefined) {
                localVarQueryParameter['email'] = email;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 회원가입 시 이메일 중복 여부를 확인합니다. 사용 가능한 이메일인 경우 available: true를 반환합니다.
         * @summary 이메일 중복 확인
         * @param {string} email 확인할 이메일 주소
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkEmailAvailability_1: async (email: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'email' is not null or undefined
            assertParamExists('checkEmailAvailability_1', 'email', email)
            const localVarPath = `/auth/check-email`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (email !== undefined) {
                localVarQueryParameter['email'] = email;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 이메일과 비밀번호를 사용하여 로그인합니다. admin@admin.com으로 로그인하면 관리자 권한을 부여받습니다. 성공 시 JWT 토큰과 사용자 정보를 반환합니다.
         * @summary 사용자 로그인
         * @param {Login} login 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginUser: async (login: Login, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'login' is not null or undefined
            assertParamExists('loginUser', 'login', login)
            const localVarPath = `/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(login, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 이메일과 비밀번호를 사용하여 로그인합니다. admin@admin.com으로 로그인하면 관리자 권한을 부여받습니다. 성공 시 JWT 토큰과 사용자 정보를 반환합니다.
         * @summary 사용자 로그인
         * @param {Login} login 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginUser_2: async (login: Login, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'login' is not null or undefined
            assertParamExists('loginUser_2', 'login', login)
            const localVarPath = `/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(login, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 새로운 사용자 계정을 생성합니다. 모든 신규 가입자는 일반 사용자(role: user) 권한으로 생성됩니다. 이메일 중복 확인 후 계정을 생성하며, 성공 시 JWT 토큰과 사용자 정보를 반환합니다.
         * @summary 회원가입
         * @param {Signup} signup 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signupUser: async (signup: Signup, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'signup' is not null or undefined
            assertParamExists('signupUser', 'signup', signup)
            const localVarPath = `/auth/signup`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(signup, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 새로운 사용자 계정을 생성합니다. 모든 신규 가입자는 일반 사용자(role: user) 권한으로 생성됩니다. 이메일 중복 확인 후 계정을 생성하며, 성공 시 JWT 토큰과 사용자 정보를 반환합니다.
         * @summary 회원가입
         * @param {Signup} signup 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signupUser_3: async (signup: Signup, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'signup' is not null or undefined
            assertParamExists('signupUser_3', 'signup', signup)
            const localVarPath = `/auth/signup`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(signup, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * 회원가입 시 이메일 중복 여부를 확인합니다. 사용 가능한 이메일인 경우 available: true를 반환합니다.
         * @summary 이메일 중복 확인
         * @param {string} email 확인할 이메일 주소
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async checkEmailAvailability(email: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CheckEmailAvailability200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.checkEmailAvailability(email, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.checkEmailAvailability']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 회원가입 시 이메일 중복 여부를 확인합니다. 사용 가능한 이메일인 경우 available: true를 반환합니다.
         * @summary 이메일 중복 확인
         * @param {string} email 확인할 이메일 주소
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async checkEmailAvailability_1(email: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CheckEmailAvailability200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.checkEmailAvailability_1(email, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.checkEmailAvailability_1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 이메일과 비밀번호를 사용하여 로그인합니다. admin@admin.com으로 로그인하면 관리자 권한을 부여받습니다. 성공 시 JWT 토큰과 사용자 정보를 반환합니다.
         * @summary 사용자 로그인
         * @param {Login} login 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async loginUser(login: Login, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LoginUser200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.loginUser(login, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.loginUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 이메일과 비밀번호를 사용하여 로그인합니다. admin@admin.com으로 로그인하면 관리자 권한을 부여받습니다. 성공 시 JWT 토큰과 사용자 정보를 반환합니다.
         * @summary 사용자 로그인
         * @param {Login} login 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async loginUser_2(login: Login, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LoginUser200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.loginUser_2(login, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.loginUser_2']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 새로운 사용자 계정을 생성합니다. 모든 신규 가입자는 일반 사용자(role: user) 권한으로 생성됩니다. 이메일 중복 확인 후 계정을 생성하며, 성공 시 JWT 토큰과 사용자 정보를 반환합니다.
         * @summary 회원가입
         * @param {Signup} signup 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async signupUser(signup: Signup, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SignupUser201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.signupUser(signup, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.signupUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 새로운 사용자 계정을 생성합니다. 모든 신규 가입자는 일반 사용자(role: user) 권한으로 생성됩니다. 이메일 중복 확인 후 계정을 생성하며, 성공 시 JWT 토큰과 사용자 정보를 반환합니다.
         * @summary 회원가입
         * @param {Signup} signup 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async signupUser_3(signup: Signup, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SignupUser201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.signupUser_3(signup, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.signupUser_3']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * 회원가입 시 이메일 중복 여부를 확인합니다. 사용 가능한 이메일인 경우 available: true를 반환합니다.
         * @summary 이메일 중복 확인
         * @param {string} email 확인할 이메일 주소
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkEmailAvailability(email: string, options?: RawAxiosRequestConfig): AxiosPromise<CheckEmailAvailability200Response> {
            return localVarFp.checkEmailAvailability(email, options).then((request) => request(axios, basePath));
        },
        /**
         * 회원가입 시 이메일 중복 여부를 확인합니다. 사용 가능한 이메일인 경우 available: true를 반환합니다.
         * @summary 이메일 중복 확인
         * @param {string} email 확인할 이메일 주소
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkEmailAvailability_1(email: string, options?: RawAxiosRequestConfig): AxiosPromise<CheckEmailAvailability200Response> {
            return localVarFp.checkEmailAvailability_1(email, options).then((request) => request(axios, basePath));
        },
        /**
         * 이메일과 비밀번호를 사용하여 로그인합니다. admin@admin.com으로 로그인하면 관리자 권한을 부여받습니다. 성공 시 JWT 토큰과 사용자 정보를 반환합니다.
         * @summary 사용자 로그인
         * @param {Login} login 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginUser(login: Login, options?: RawAxiosRequestConfig): AxiosPromise<LoginUser200Response> {
            return localVarFp.loginUser(login, options).then((request) => request(axios, basePath));
        },
        /**
         * 이메일과 비밀번호를 사용하여 로그인합니다. admin@admin.com으로 로그인하면 관리자 권한을 부여받습니다. 성공 시 JWT 토큰과 사용자 정보를 반환합니다.
         * @summary 사용자 로그인
         * @param {Login} login 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginUser_2(login: Login, options?: RawAxiosRequestConfig): AxiosPromise<LoginUser200Response> {
            return localVarFp.loginUser_2(login, options).then((request) => request(axios, basePath));
        },
        /**
         * 새로운 사용자 계정을 생성합니다. 모든 신규 가입자는 일반 사용자(role: user) 권한으로 생성됩니다. 이메일 중복 확인 후 계정을 생성하며, 성공 시 JWT 토큰과 사용자 정보를 반환합니다.
         * @summary 회원가입
         * @param {Signup} signup 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signupUser(signup: Signup, options?: RawAxiosRequestConfig): AxiosPromise<SignupUser201Response> {
            return localVarFp.signupUser(signup, options).then((request) => request(axios, basePath));
        },
        /**
         * 새로운 사용자 계정을 생성합니다. 모든 신규 가입자는 일반 사용자(role: user) 권한으로 생성됩니다. 이메일 중복 확인 후 계정을 생성하며, 성공 시 JWT 토큰과 사용자 정보를 반환합니다.
         * @summary 회원가입
         * @param {Signup} signup 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signupUser_3(signup: Signup, options?: RawAxiosRequestConfig): AxiosPromise<SignupUser201Response> {
            return localVarFp.signupUser_3(signup, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
    /**
     * 회원가입 시 이메일 중복 여부를 확인합니다. 사용 가능한 이메일인 경우 available: true를 반환합니다.
     * @summary 이메일 중복 확인
     * @param {string} email 확인할 이메일 주소
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public checkEmailAvailability(email: string, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).checkEmailAvailability(email, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 회원가입 시 이메일 중복 여부를 확인합니다. 사용 가능한 이메일인 경우 available: true를 반환합니다.
     * @summary 이메일 중복 확인
     * @param {string} email 확인할 이메일 주소
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public checkEmailAvailability_1(email: string, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).checkEmailAvailability_1(email, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 이메일과 비밀번호를 사용하여 로그인합니다. admin@admin.com으로 로그인하면 관리자 권한을 부여받습니다. 성공 시 JWT 토큰과 사용자 정보를 반환합니다.
     * @summary 사용자 로그인
     * @param {Login} login 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public loginUser(login: Login, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).loginUser(login, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 이메일과 비밀번호를 사용하여 로그인합니다. admin@admin.com으로 로그인하면 관리자 권한을 부여받습니다. 성공 시 JWT 토큰과 사용자 정보를 반환합니다.
     * @summary 사용자 로그인
     * @param {Login} login 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public loginUser_2(login: Login, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).loginUser_2(login, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 새로운 사용자 계정을 생성합니다. 모든 신규 가입자는 일반 사용자(role: user) 권한으로 생성됩니다. 이메일 중복 확인 후 계정을 생성하며, 성공 시 JWT 토큰과 사용자 정보를 반환합니다.
     * @summary 회원가입
     * @param {Signup} signup 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public signupUser(signup: Signup, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).signupUser(signup, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 새로운 사용자 계정을 생성합니다. 모든 신규 가입자는 일반 사용자(role: user) 권한으로 생성됩니다. 이메일 중복 확인 후 계정을 생성하며, 성공 시 JWT 토큰과 사용자 정보를 반환합니다.
     * @summary 회원가입
     * @param {Signup} signup 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public signupUser_3(signup: Signup, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).signupUser_3(signup, options).then((request) => request(this.axios, this.basePath));
    }
}

