/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateRental } from '../models';
// @ts-ignore
import type { CreateRental201Response } from '../models';
// @ts-ignore
import type { GetUserRentals200Response } from '../models';
// @ts-ignore
import type { ReturnRental } from '../models';
// @ts-ignore
import type { ReturnRental200Response } from '../models';
/**
 * RentalsApi - axios parameter creator
 * @export
 */
export const RentalsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 지정된 대여소에서 자전거를 대여합니다. 사용자는 한 번에 하나의 자전거만 대여할 수 있습니다. 대여소에 자전거가 없거나 이미 대여 중인 경우 실패합니다. 관리자는 대여할 수 없습니다.
         * @summary 자전거 대여
         * @param {CreateRental} createRental 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRental: async (createRental: CreateRental, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createRental' is not null or undefined
            assertParamExists('createRental', 'createRental', createRental)
            const localVarPath = `/rentals`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createRental, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 지정된 대여소에서 자전거를 대여합니다. 사용자는 한 번에 하나의 자전거만 대여할 수 있습니다. 대여소에 자전거가 없거나 이미 대여 중인 경우 실패합니다. 관리자는 대여할 수 없습니다.
         * @summary 자전거 대여
         * @param {CreateRental} createRental 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRental_1: async (createRental: CreateRental, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createRental' is not null or undefined
            assertParamExists('createRental_1', 'createRental', createRental)
            const localVarPath = `/rentals`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createRental, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 특정 사용자의 대여 이력을 조회합니다. 페이지네이션을 지원하며, 최신 대여 순으로 정렬됩니다. 각 대여 기록에는 출발/도착 대여소, 이용 시간, 이동 거리가 포함됩니다.
         * @summary 사용자 대여 이력 조회
         * @param {string} userId 사용자 ID
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserRentals: async (userId: string, page?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserRentals', 'userId', userId)
            const localVarPath = `/users/{userId}/rentals`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 특정 사용자의 대여 이력을 조회합니다. 페이지네이션을 지원하며, 최신 대여 순으로 정렬됩니다. 각 대여 기록에는 출발/도착 대여소, 이용 시간, 이동 거리가 포함됩니다.
         * @summary 사용자 대여 이력 조회
         * @param {string} userId 사용자 ID
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserRentals_2: async (userId: string, page?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserRentals_2', 'userId', userId)
            const localVarPath = `/users/{userId}/rentals`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 대여한 자전거를 지정된 대여소에 반납합니다. 반납 시 이용 시간과 이동 거리가 자동으로 계산됩니다. 반납 정보는 사용자의 대여 이력에 저장됩니다.
         * @summary 자전거 반납
         * @param {string} rentalId 
         * @param {ReturnRental} returnRental 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        returnRental: async (rentalId: string, returnRental: ReturnRental, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'rentalId' is not null or undefined
            assertParamExists('returnRental', 'rentalId', rentalId)
            // verify required parameter 'returnRental' is not null or undefined
            assertParamExists('returnRental', 'returnRental', returnRental)
            const localVarPath = `/rentals/{rentalId}/return`
                .replace(`{${"rentalId"}}`, encodeURIComponent(String(rentalId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(returnRental, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 대여한 자전거를 지정된 대여소에 반납합니다. 반납 시 이용 시간과 이동 거리가 자동으로 계산됩니다. 반납 정보는 사용자의 대여 이력에 저장됩니다.
         * @summary 자전거 반납
         * @param {string} rentalId 
         * @param {ReturnRental} returnRental 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        returnRental_3: async (rentalId: string, returnRental: ReturnRental, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'rentalId' is not null or undefined
            assertParamExists('returnRental_3', 'rentalId', rentalId)
            // verify required parameter 'returnRental' is not null or undefined
            assertParamExists('returnRental_3', 'returnRental', returnRental)
            const localVarPath = `/rentals/{rentalId}/return`
                .replace(`{${"rentalId"}}`, encodeURIComponent(String(rentalId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(returnRental, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RentalsApi - functional programming interface
 * @export
 */
export const RentalsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RentalsApiAxiosParamCreator(configuration)
    return {
        /**
         * 지정된 대여소에서 자전거를 대여합니다. 사용자는 한 번에 하나의 자전거만 대여할 수 있습니다. 대여소에 자전거가 없거나 이미 대여 중인 경우 실패합니다. 관리자는 대여할 수 없습니다.
         * @summary 자전거 대여
         * @param {CreateRental} createRental 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createRental(createRental: CreateRental, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateRental201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createRental(createRental, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RentalsApi.createRental']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 지정된 대여소에서 자전거를 대여합니다. 사용자는 한 번에 하나의 자전거만 대여할 수 있습니다. 대여소에 자전거가 없거나 이미 대여 중인 경우 실패합니다. 관리자는 대여할 수 없습니다.
         * @summary 자전거 대여
         * @param {CreateRental} createRental 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createRental_1(createRental: CreateRental, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateRental201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createRental_1(createRental, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RentalsApi.createRental_1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 특정 사용자의 대여 이력을 조회합니다. 페이지네이션을 지원하며, 최신 대여 순으로 정렬됩니다. 각 대여 기록에는 출발/도착 대여소, 이용 시간, 이동 거리가 포함됩니다.
         * @summary 사용자 대여 이력 조회
         * @param {string} userId 사용자 ID
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserRentals(userId: string, page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserRentals200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserRentals(userId, page, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RentalsApi.getUserRentals']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 특정 사용자의 대여 이력을 조회합니다. 페이지네이션을 지원하며, 최신 대여 순으로 정렬됩니다. 각 대여 기록에는 출발/도착 대여소, 이용 시간, 이동 거리가 포함됩니다.
         * @summary 사용자 대여 이력 조회
         * @param {string} userId 사용자 ID
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserRentals_2(userId: string, page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserRentals200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserRentals_2(userId, page, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RentalsApi.getUserRentals_2']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 대여한 자전거를 지정된 대여소에 반납합니다. 반납 시 이용 시간과 이동 거리가 자동으로 계산됩니다. 반납 정보는 사용자의 대여 이력에 저장됩니다.
         * @summary 자전거 반납
         * @param {string} rentalId 
         * @param {ReturnRental} returnRental 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async returnRental(rentalId: string, returnRental: ReturnRental, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ReturnRental200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.returnRental(rentalId, returnRental, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RentalsApi.returnRental']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 대여한 자전거를 지정된 대여소에 반납합니다. 반납 시 이용 시간과 이동 거리가 자동으로 계산됩니다. 반납 정보는 사용자의 대여 이력에 저장됩니다.
         * @summary 자전거 반납
         * @param {string} rentalId 
         * @param {ReturnRental} returnRental 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async returnRental_3(rentalId: string, returnRental: ReturnRental, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ReturnRental200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.returnRental_3(rentalId, returnRental, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RentalsApi.returnRental_3']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RentalsApi - factory interface
 * @export
 */
export const RentalsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RentalsApiFp(configuration)
    return {
        /**
         * 지정된 대여소에서 자전거를 대여합니다. 사용자는 한 번에 하나의 자전거만 대여할 수 있습니다. 대여소에 자전거가 없거나 이미 대여 중인 경우 실패합니다. 관리자는 대여할 수 없습니다.
         * @summary 자전거 대여
         * @param {CreateRental} createRental 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRental(createRental: CreateRental, options?: RawAxiosRequestConfig): AxiosPromise<CreateRental201Response> {
            return localVarFp.createRental(createRental, options).then((request) => request(axios, basePath));
        },
        /**
         * 지정된 대여소에서 자전거를 대여합니다. 사용자는 한 번에 하나의 자전거만 대여할 수 있습니다. 대여소에 자전거가 없거나 이미 대여 중인 경우 실패합니다. 관리자는 대여할 수 없습니다.
         * @summary 자전거 대여
         * @param {CreateRental} createRental 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRental_1(createRental: CreateRental, options?: RawAxiosRequestConfig): AxiosPromise<CreateRental201Response> {
            return localVarFp.createRental_1(createRental, options).then((request) => request(axios, basePath));
        },
        /**
         * 특정 사용자의 대여 이력을 조회합니다. 페이지네이션을 지원하며, 최신 대여 순으로 정렬됩니다. 각 대여 기록에는 출발/도착 대여소, 이용 시간, 이동 거리가 포함됩니다.
         * @summary 사용자 대여 이력 조회
         * @param {string} userId 사용자 ID
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserRentals(userId: string, page?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<GetUserRentals200Response> {
            return localVarFp.getUserRentals(userId, page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 특정 사용자의 대여 이력을 조회합니다. 페이지네이션을 지원하며, 최신 대여 순으로 정렬됩니다. 각 대여 기록에는 출발/도착 대여소, 이용 시간, 이동 거리가 포함됩니다.
         * @summary 사용자 대여 이력 조회
         * @param {string} userId 사용자 ID
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserRentals_2(userId: string, page?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<GetUserRentals200Response> {
            return localVarFp.getUserRentals_2(userId, page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 대여한 자전거를 지정된 대여소에 반납합니다. 반납 시 이용 시간과 이동 거리가 자동으로 계산됩니다. 반납 정보는 사용자의 대여 이력에 저장됩니다.
         * @summary 자전거 반납
         * @param {string} rentalId 
         * @param {ReturnRental} returnRental 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        returnRental(rentalId: string, returnRental: ReturnRental, options?: RawAxiosRequestConfig): AxiosPromise<ReturnRental200Response> {
            return localVarFp.returnRental(rentalId, returnRental, options).then((request) => request(axios, basePath));
        },
        /**
         * 대여한 자전거를 지정된 대여소에 반납합니다. 반납 시 이용 시간과 이동 거리가 자동으로 계산됩니다. 반납 정보는 사용자의 대여 이력에 저장됩니다.
         * @summary 자전거 반납
         * @param {string} rentalId 
         * @param {ReturnRental} returnRental 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        returnRental_3(rentalId: string, returnRental: ReturnRental, options?: RawAxiosRequestConfig): AxiosPromise<ReturnRental200Response> {
            return localVarFp.returnRental_3(rentalId, returnRental, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RentalsApi - object-oriented interface
 * @export
 * @class RentalsApi
 * @extends {BaseAPI}
 */
export class RentalsApi extends BaseAPI {
    /**
     * 지정된 대여소에서 자전거를 대여합니다. 사용자는 한 번에 하나의 자전거만 대여할 수 있습니다. 대여소에 자전거가 없거나 이미 대여 중인 경우 실패합니다. 관리자는 대여할 수 없습니다.
     * @summary 자전거 대여
     * @param {CreateRental} createRental 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RentalsApi
     */
    public createRental(createRental: CreateRental, options?: RawAxiosRequestConfig) {
        return RentalsApiFp(this.configuration).createRental(createRental, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 지정된 대여소에서 자전거를 대여합니다. 사용자는 한 번에 하나의 자전거만 대여할 수 있습니다. 대여소에 자전거가 없거나 이미 대여 중인 경우 실패합니다. 관리자는 대여할 수 없습니다.
     * @summary 자전거 대여
     * @param {CreateRental} createRental 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RentalsApi
     */
    public createRental_1(createRental: CreateRental, options?: RawAxiosRequestConfig) {
        return RentalsApiFp(this.configuration).createRental_1(createRental, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 특정 사용자의 대여 이력을 조회합니다. 페이지네이션을 지원하며, 최신 대여 순으로 정렬됩니다. 각 대여 기록에는 출발/도착 대여소, 이용 시간, 이동 거리가 포함됩니다.
     * @summary 사용자 대여 이력 조회
     * @param {string} userId 사용자 ID
     * @param {number} [page] 페이지 번호 (1부터 시작)
     * @param {number} [limit] 페이지당 항목 수
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RentalsApi
     */
    public getUserRentals(userId: string, page?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return RentalsApiFp(this.configuration).getUserRentals(userId, page, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 특정 사용자의 대여 이력을 조회합니다. 페이지네이션을 지원하며, 최신 대여 순으로 정렬됩니다. 각 대여 기록에는 출발/도착 대여소, 이용 시간, 이동 거리가 포함됩니다.
     * @summary 사용자 대여 이력 조회
     * @param {string} userId 사용자 ID
     * @param {number} [page] 페이지 번호 (1부터 시작)
     * @param {number} [limit] 페이지당 항목 수
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RentalsApi
     */
    public getUserRentals_2(userId: string, page?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return RentalsApiFp(this.configuration).getUserRentals_2(userId, page, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 대여한 자전거를 지정된 대여소에 반납합니다. 반납 시 이용 시간과 이동 거리가 자동으로 계산됩니다. 반납 정보는 사용자의 대여 이력에 저장됩니다.
     * @summary 자전거 반납
     * @param {string} rentalId 
     * @param {ReturnRental} returnRental 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RentalsApi
     */
    public returnRental(rentalId: string, returnRental: ReturnRental, options?: RawAxiosRequestConfig) {
        return RentalsApiFp(this.configuration).returnRental(rentalId, returnRental, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 대여한 자전거를 지정된 대여소에 반납합니다. 반납 시 이용 시간과 이동 거리가 자동으로 계산됩니다. 반납 정보는 사용자의 대여 이력에 저장됩니다.
     * @summary 자전거 반납
     * @param {string} rentalId 
     * @param {ReturnRental} returnRental 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RentalsApi
     */
    public returnRental_3(rentalId: string, returnRental: ReturnRental, options?: RawAxiosRequestConfig) {
        return RentalsApiFp(this.configuration).returnRental_3(rentalId, returnRental, options).then((request) => request(this.axios, this.basePath));
    }
}

