/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CalculateRoute } from '../models';
// @ts-ignore
import type { CalculateRoute200Response } from '../models';
// @ts-ignore
import type { GeocodeAddress200Response } from '../models';
/**
 * RoutesApi - axios parameter creator
 * @export
 */
export const RoutesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 출발지와 목적지 좌표를 기반으로 자전거 이용 최적 경로를 계산합니다. Haversine 공식을 사용하여 거리를 계산하고, 가장 가까운 대여소와 반납 대여소를 추천합니다.
         * @summary 최적 경로 계산
         * @param {CalculateRoute} calculateRoute 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calculateRoute: async (calculateRoute: CalculateRoute, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'calculateRoute' is not null or undefined
            assertParamExists('calculateRoute', 'calculateRoute', calculateRoute)
            const localVarPath = `/routes/calculate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(calculateRoute, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 출발지와 목적지 좌표를 기반으로 자전거 이용 최적 경로를 계산합니다. Haversine 공식을 사용하여 거리를 계산하고, 가장 가까운 대여소와 반납 대여소를 추천합니다.
         * @summary 최적 경로 계산
         * @param {CalculateRoute} calculateRoute 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calculateRoute_1: async (calculateRoute: CalculateRoute, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'calculateRoute' is not null or undefined
            assertParamExists('calculateRoute_1', 'calculateRoute', calculateRoute)
            const localVarPath = `/routes/calculate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(calculateRoute, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 주소 문자열을 위도/경도 좌표로 변환합니다. 현재는 해시 기반 모의 지오코딩을 사용합니다.
         * @summary 주소를 좌표로 변환
         * @param {string} address 변환할 주소
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        geocodeAddress: async (address: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'address' is not null or undefined
            assertParamExists('geocodeAddress', 'address', address)
            const localVarPath = `/geocode`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (address !== undefined) {
                localVarQueryParameter['address'] = address;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 주소 문자열을 위도/경도 좌표로 변환합니다. 현재는 해시 기반 모의 지오코딩을 사용합니다.
         * @summary 주소를 좌표로 변환
         * @param {string} address 변환할 주소
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        geocodeAddress_2: async (address: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'address' is not null or undefined
            assertParamExists('geocodeAddress_2', 'address', address)
            const localVarPath = `/geocode`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (address !== undefined) {
                localVarQueryParameter['address'] = address;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RoutesApi - functional programming interface
 * @export
 */
export const RoutesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RoutesApiAxiosParamCreator(configuration)
    return {
        /**
         * 출발지와 목적지 좌표를 기반으로 자전거 이용 최적 경로를 계산합니다. Haversine 공식을 사용하여 거리를 계산하고, 가장 가까운 대여소와 반납 대여소를 추천합니다.
         * @summary 최적 경로 계산
         * @param {CalculateRoute} calculateRoute 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async calculateRoute(calculateRoute: CalculateRoute, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CalculateRoute200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.calculateRoute(calculateRoute, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoutesApi.calculateRoute']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 출발지와 목적지 좌표를 기반으로 자전거 이용 최적 경로를 계산합니다. Haversine 공식을 사용하여 거리를 계산하고, 가장 가까운 대여소와 반납 대여소를 추천합니다.
         * @summary 최적 경로 계산
         * @param {CalculateRoute} calculateRoute 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async calculateRoute_1(calculateRoute: CalculateRoute, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CalculateRoute200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.calculateRoute_1(calculateRoute, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoutesApi.calculateRoute_1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 주소 문자열을 위도/경도 좌표로 변환합니다. 현재는 해시 기반 모의 지오코딩을 사용합니다.
         * @summary 주소를 좌표로 변환
         * @param {string} address 변환할 주소
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async geocodeAddress(address: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GeocodeAddress200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.geocodeAddress(address, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoutesApi.geocodeAddress']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 주소 문자열을 위도/경도 좌표로 변환합니다. 현재는 해시 기반 모의 지오코딩을 사용합니다.
         * @summary 주소를 좌표로 변환
         * @param {string} address 변환할 주소
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async geocodeAddress_2(address: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GeocodeAddress200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.geocodeAddress_2(address, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoutesApi.geocodeAddress_2']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RoutesApi - factory interface
 * @export
 */
export const RoutesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RoutesApiFp(configuration)
    return {
        /**
         * 출발지와 목적지 좌표를 기반으로 자전거 이용 최적 경로를 계산합니다. Haversine 공식을 사용하여 거리를 계산하고, 가장 가까운 대여소와 반납 대여소를 추천합니다.
         * @summary 최적 경로 계산
         * @param {CalculateRoute} calculateRoute 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calculateRoute(calculateRoute: CalculateRoute, options?: RawAxiosRequestConfig): AxiosPromise<CalculateRoute200Response> {
            return localVarFp.calculateRoute(calculateRoute, options).then((request) => request(axios, basePath));
        },
        /**
         * 출발지와 목적지 좌표를 기반으로 자전거 이용 최적 경로를 계산합니다. Haversine 공식을 사용하여 거리를 계산하고, 가장 가까운 대여소와 반납 대여소를 추천합니다.
         * @summary 최적 경로 계산
         * @param {CalculateRoute} calculateRoute 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calculateRoute_1(calculateRoute: CalculateRoute, options?: RawAxiosRequestConfig): AxiosPromise<CalculateRoute200Response> {
            return localVarFp.calculateRoute_1(calculateRoute, options).then((request) => request(axios, basePath));
        },
        /**
         * 주소 문자열을 위도/경도 좌표로 변환합니다. 현재는 해시 기반 모의 지오코딩을 사용합니다.
         * @summary 주소를 좌표로 변환
         * @param {string} address 변환할 주소
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        geocodeAddress(address: string, options?: RawAxiosRequestConfig): AxiosPromise<GeocodeAddress200Response> {
            return localVarFp.geocodeAddress(address, options).then((request) => request(axios, basePath));
        },
        /**
         * 주소 문자열을 위도/경도 좌표로 변환합니다. 현재는 해시 기반 모의 지오코딩을 사용합니다.
         * @summary 주소를 좌표로 변환
         * @param {string} address 변환할 주소
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        geocodeAddress_2(address: string, options?: RawAxiosRequestConfig): AxiosPromise<GeocodeAddress200Response> {
            return localVarFp.geocodeAddress_2(address, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RoutesApi - object-oriented interface
 * @export
 * @class RoutesApi
 * @extends {BaseAPI}
 */
export class RoutesApi extends BaseAPI {
    /**
     * 출발지와 목적지 좌표를 기반으로 자전거 이용 최적 경로를 계산합니다. Haversine 공식을 사용하여 거리를 계산하고, 가장 가까운 대여소와 반납 대여소를 추천합니다.
     * @summary 최적 경로 계산
     * @param {CalculateRoute} calculateRoute 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoutesApi
     */
    public calculateRoute(calculateRoute: CalculateRoute, options?: RawAxiosRequestConfig) {
        return RoutesApiFp(this.configuration).calculateRoute(calculateRoute, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 출발지와 목적지 좌표를 기반으로 자전거 이용 최적 경로를 계산합니다. Haversine 공식을 사용하여 거리를 계산하고, 가장 가까운 대여소와 반납 대여소를 추천합니다.
     * @summary 최적 경로 계산
     * @param {CalculateRoute} calculateRoute 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoutesApi
     */
    public calculateRoute_1(calculateRoute: CalculateRoute, options?: RawAxiosRequestConfig) {
        return RoutesApiFp(this.configuration).calculateRoute_1(calculateRoute, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 주소 문자열을 위도/경도 좌표로 변환합니다. 현재는 해시 기반 모의 지오코딩을 사용합니다.
     * @summary 주소를 좌표로 변환
     * @param {string} address 변환할 주소
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoutesApi
     */
    public geocodeAddress(address: string, options?: RawAxiosRequestConfig) {
        return RoutesApiFp(this.configuration).geocodeAddress(address, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 주소 문자열을 위도/경도 좌표로 변환합니다. 현재는 해시 기반 모의 지오코딩을 사용합니다.
     * @summary 주소를 좌표로 변환
     * @param {string} address 변환할 주소
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoutesApi
     */
    public geocodeAddress_2(address: string, options?: RawAxiosRequestConfig) {
        return RoutesApiFp(this.configuration).geocodeAddress_2(address, options).then((request) => request(this.axios, this.basePath));
    }
}

