/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ChangePassword } from '../models';
// @ts-ignore
import type { GetUserById200Response } from '../models';
// @ts-ignore
import type { GetUserRentals200Response } from '../models';
// @ts-ignore
import type { GetUserStatistics200Response } from '../models';
// @ts-ignore
import type { Update } from '../models';
/**
 * UsersApi - axios parameter creator
 * @export
 */
export const UsersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 사용자의 비밀번호를 변경합니다. 현재 비밀번호 확인이 필요합니다.
         * @summary 비밀번호 변경
         * @param {string} userId 사용자 ID
         * @param {ChangePassword} changePassword 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changePassword: async (userId: string, changePassword: ChangePassword, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('changePassword', 'userId', userId)
            // verify required parameter 'changePassword' is not null or undefined
            assertParamExists('changePassword', 'changePassword', changePassword)
            const localVarPath = `/users/{userId}/password`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(changePassword, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 사용자의 비밀번호를 변경합니다. 현재 비밀번호 확인이 필요합니다.
         * @summary 비밀번호 변경
         * @param {string} userId 사용자 ID
         * @param {ChangePassword} changePassword 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changePassword_1: async (userId: string, changePassword: ChangePassword, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('changePassword_1', 'userId', userId)
            // verify required parameter 'changePassword' is not null or undefined
            assertParamExists('changePassword_1', 'changePassword', changePassword)
            const localVarPath = `/users/{userId}/password`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(changePassword, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 특정 사용자의 프로필 정보를 조회합니다.
         * @summary 사용자 정보 조회
         * @param {string} userId 사용자 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserById: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserById', 'userId', userId)
            const localVarPath = `/users/{userId}/profile`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 특정 사용자의 프로필 정보를 조회합니다.
         * @summary 사용자 정보 조회
         * @param {string} userId 사용자 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserById_2: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserById_2', 'userId', userId)
            const localVarPath = `/users/{userId}/profile`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 특정 사용자의 대여 이력을 조회합니다. 페이지네이션을 지원하며, 최신 대여 순으로 정렬됩니다. 각 대여 기록에는 출발/도착 대여소, 이용 시간, 이동 거리가 포함됩니다.
         * @summary 사용자 대여 이력 조회
         * @param {string} userId 사용자 ID
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserRentals: async (userId: string, page?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserRentals', 'userId', userId)
            const localVarPath = `/users/{userId}/rentals`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 사용자의 자전거 이용 통계를 조회합니다. 총 대여 횟수, 총 이동 거리, 총 이용 시간, 평균값 등을 포함합니다.
         * @summary 사용자 통계 조회
         * @param {string} userId 사용자 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserStatistics: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserStatistics', 'userId', userId)
            const localVarPath = `/users/{userId}/statistics`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 사용자의 자전거 이용 통계를 조회합니다. 총 대여 횟수, 총 이동 거리, 총 이용 시간, 평균값 등을 포함합니다.
         * @summary 사용자 통계 조회
         * @param {string} userId 사용자 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserStatistics_3: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserStatistics_3', 'userId', userId)
            const localVarPath = `/users/{userId}/statistics`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 사용자의 프로필 정보를 수정합니다. 본인 또는 관리자만 수정할 수 있습니다.
         * @summary 사용자 정보 수정
         * @param {string} userId 사용자 ID
         * @param {Update} update 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUser: async (userId: string, update: Update, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('updateUser', 'userId', userId)
            // verify required parameter 'update' is not null or undefined
            assertParamExists('updateUser', 'update', update)
            const localVarPath = `/users/{userId}`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(update, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 사용자의 프로필 정보를 수정합니다. 본인 또는 관리자만 수정할 수 있습니다.
         * @summary 사용자 정보 수정
         * @param {string} userId 사용자 ID
         * @param {Update} update 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUser_4: async (userId: string, update: Update, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('updateUser_4', 'userId', userId)
            // verify required parameter 'update' is not null or undefined
            assertParamExists('updateUser_4', 'update', update)
            const localVarPath = `/users/{userId}`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(update, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsersApi - functional programming interface
 * @export
 */
export const UsersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UsersApiAxiosParamCreator(configuration)
    return {
        /**
         * 사용자의 비밀번호를 변경합니다. 현재 비밀번호 확인이 필요합니다.
         * @summary 비밀번호 변경
         * @param {string} userId 사용자 ID
         * @param {ChangePassword} changePassword 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async changePassword(userId: string, changePassword: ChangePassword, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.changePassword(userId, changePassword, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.changePassword']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 사용자의 비밀번호를 변경합니다. 현재 비밀번호 확인이 필요합니다.
         * @summary 비밀번호 변경
         * @param {string} userId 사용자 ID
         * @param {ChangePassword} changePassword 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async changePassword_1(userId: string, changePassword: ChangePassword, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.changePassword_1(userId, changePassword, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.changePassword_1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 특정 사용자의 프로필 정보를 조회합니다.
         * @summary 사용자 정보 조회
         * @param {string} userId 사용자 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserById(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserById200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserById(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getUserById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 특정 사용자의 프로필 정보를 조회합니다.
         * @summary 사용자 정보 조회
         * @param {string} userId 사용자 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserById_2(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserById200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserById_2(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getUserById_2']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 특정 사용자의 대여 이력을 조회합니다. 페이지네이션을 지원하며, 최신 대여 순으로 정렬됩니다. 각 대여 기록에는 출발/도착 대여소, 이용 시간, 이동 거리가 포함됩니다.
         * @summary 사용자 대여 이력 조회
         * @param {string} userId 사용자 ID
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserRentals(userId: string, page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserRentals200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserRentals(userId, page, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getUserRentals']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 사용자의 자전거 이용 통계를 조회합니다. 총 대여 횟수, 총 이동 거리, 총 이용 시간, 평균값 등을 포함합니다.
         * @summary 사용자 통계 조회
         * @param {string} userId 사용자 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserStatistics(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserStatistics200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserStatistics(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getUserStatistics']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 사용자의 자전거 이용 통계를 조회합니다. 총 대여 횟수, 총 이동 거리, 총 이용 시간, 평균값 등을 포함합니다.
         * @summary 사용자 통계 조회
         * @param {string} userId 사용자 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserStatistics_3(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserStatistics200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserStatistics_3(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getUserStatistics_3']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 사용자의 프로필 정보를 수정합니다. 본인 또는 관리자만 수정할 수 있습니다.
         * @summary 사용자 정보 수정
         * @param {string} userId 사용자 ID
         * @param {Update} update 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateUser(userId: string, update: Update, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserById200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateUser(userId, update, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.updateUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 사용자의 프로필 정보를 수정합니다. 본인 또는 관리자만 수정할 수 있습니다.
         * @summary 사용자 정보 수정
         * @param {string} userId 사용자 ID
         * @param {Update} update 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateUser_4(userId: string, update: Update, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserById200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateUser_4(userId, update, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.updateUser_4']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UsersApi - factory interface
 * @export
 */
export const UsersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UsersApiFp(configuration)
    return {
        /**
         * 사용자의 비밀번호를 변경합니다. 현재 비밀번호 확인이 필요합니다.
         * @summary 비밀번호 변경
         * @param {string} userId 사용자 ID
         * @param {ChangePassword} changePassword 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changePassword(userId: string, changePassword: ChangePassword, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.changePassword(userId, changePassword, options).then((request) => request(axios, basePath));
        },
        /**
         * 사용자의 비밀번호를 변경합니다. 현재 비밀번호 확인이 필요합니다.
         * @summary 비밀번호 변경
         * @param {string} userId 사용자 ID
         * @param {ChangePassword} changePassword 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changePassword_1(userId: string, changePassword: ChangePassword, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.changePassword_1(userId, changePassword, options).then((request) => request(axios, basePath));
        },
        /**
         * 특정 사용자의 프로필 정보를 조회합니다.
         * @summary 사용자 정보 조회
         * @param {string} userId 사용자 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserById(userId: string, options?: RawAxiosRequestConfig): AxiosPromise<GetUserById200Response> {
            return localVarFp.getUserById(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 특정 사용자의 프로필 정보를 조회합니다.
         * @summary 사용자 정보 조회
         * @param {string} userId 사용자 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserById_2(userId: string, options?: RawAxiosRequestConfig): AxiosPromise<GetUserById200Response> {
            return localVarFp.getUserById_2(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 특정 사용자의 대여 이력을 조회합니다. 페이지네이션을 지원하며, 최신 대여 순으로 정렬됩니다. 각 대여 기록에는 출발/도착 대여소, 이용 시간, 이동 거리가 포함됩니다.
         * @summary 사용자 대여 이력 조회
         * @param {string} userId 사용자 ID
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserRentals(userId: string, page?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<GetUserRentals200Response> {
            return localVarFp.getUserRentals(userId, page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 사용자의 자전거 이용 통계를 조회합니다. 총 대여 횟수, 총 이동 거리, 총 이용 시간, 평균값 등을 포함합니다.
         * @summary 사용자 통계 조회
         * @param {string} userId 사용자 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserStatistics(userId: string, options?: RawAxiosRequestConfig): AxiosPromise<GetUserStatistics200Response> {
            return localVarFp.getUserStatistics(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 사용자의 자전거 이용 통계를 조회합니다. 총 대여 횟수, 총 이동 거리, 총 이용 시간, 평균값 등을 포함합니다.
         * @summary 사용자 통계 조회
         * @param {string} userId 사용자 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserStatistics_3(userId: string, options?: RawAxiosRequestConfig): AxiosPromise<GetUserStatistics200Response> {
            return localVarFp.getUserStatistics_3(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 사용자의 프로필 정보를 수정합니다. 본인 또는 관리자만 수정할 수 있습니다.
         * @summary 사용자 정보 수정
         * @param {string} userId 사용자 ID
         * @param {Update} update 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUser(userId: string, update: Update, options?: RawAxiosRequestConfig): AxiosPromise<GetUserById200Response> {
            return localVarFp.updateUser(userId, update, options).then((request) => request(axios, basePath));
        },
        /**
         * 사용자의 프로필 정보를 수정합니다. 본인 또는 관리자만 수정할 수 있습니다.
         * @summary 사용자 정보 수정
         * @param {string} userId 사용자 ID
         * @param {Update} update 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUser_4(userId: string, update: Update, options?: RawAxiosRequestConfig): AxiosPromise<GetUserById200Response> {
            return localVarFp.updateUser_4(userId, update, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UsersApi - object-oriented interface
 * @export
 * @class UsersApi
 * @extends {BaseAPI}
 */
export class UsersApi extends BaseAPI {
    /**
     * 사용자의 비밀번호를 변경합니다. 현재 비밀번호 확인이 필요합니다.
     * @summary 비밀번호 변경
     * @param {string} userId 사용자 ID
     * @param {ChangePassword} changePassword 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public changePassword(userId: string, changePassword: ChangePassword, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).changePassword(userId, changePassword, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 사용자의 비밀번호를 변경합니다. 현재 비밀번호 확인이 필요합니다.
     * @summary 비밀번호 변경
     * @param {string} userId 사용자 ID
     * @param {ChangePassword} changePassword 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public changePassword_1(userId: string, changePassword: ChangePassword, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).changePassword_1(userId, changePassword, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 특정 사용자의 프로필 정보를 조회합니다.
     * @summary 사용자 정보 조회
     * @param {string} userId 사용자 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getUserById(userId: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getUserById(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 특정 사용자의 프로필 정보를 조회합니다.
     * @summary 사용자 정보 조회
     * @param {string} userId 사용자 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getUserById_2(userId: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getUserById_2(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 특정 사용자의 대여 이력을 조회합니다. 페이지네이션을 지원하며, 최신 대여 순으로 정렬됩니다. 각 대여 기록에는 출발/도착 대여소, 이용 시간, 이동 거리가 포함됩니다.
     * @summary 사용자 대여 이력 조회
     * @param {string} userId 사용자 ID
     * @param {number} [page] 페이지 번호 (1부터 시작)
     * @param {number} [limit] 페이지당 항목 수
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getUserRentals(userId: string, page?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getUserRentals(userId, page, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 사용자의 자전거 이용 통계를 조회합니다. 총 대여 횟수, 총 이동 거리, 총 이용 시간, 평균값 등을 포함합니다.
     * @summary 사용자 통계 조회
     * @param {string} userId 사용자 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getUserStatistics(userId: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getUserStatistics(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 사용자의 자전거 이용 통계를 조회합니다. 총 대여 횟수, 총 이동 거리, 총 이용 시간, 평균값 등을 포함합니다.
     * @summary 사용자 통계 조회
     * @param {string} userId 사용자 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getUserStatistics_3(userId: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getUserStatistics_3(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 사용자의 프로필 정보를 수정합니다. 본인 또는 관리자만 수정할 수 있습니다.
     * @summary 사용자 정보 수정
     * @param {string} userId 사용자 ID
     * @param {Update} update 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public updateUser(userId: string, update: Update, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).updateUser(userId, update, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 사용자의 프로필 정보를 수정합니다. 본인 또는 관리자만 수정할 수 있습니다.
     * @summary 사용자 정보 수정
     * @param {string} userId 사용자 ID
     * @param {Update} update 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public updateUser_4(userId: string, update: Update, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).updateUser_4(userId, update, options).then((request) => request(this.axios, this.basePath));
    }
}

