/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 카테고리와 사람이 읽을 수 있는 메시지를 포함하는 활동/알림 항목에 대한 스키마입니다.
 * @export
 * @interface Activity
 */
export interface Activity {
    /**
     * \'rental\'|\'repair\'|\'registeration\'|\'board\'
     * @type {string}
     * @memberof Activity
     */
    'category': ActivityCategoryEnum;
    /**
     * {사용자이름}이 {행동}을 했습니다
     * @type {string}
     * @memberof Activity
     */
    'content': string;
    /**
     * 생성시간
     * @type {string}
     * @memberof Activity
     */
    'time': string;
}

export const ActivityCategoryEnum = {
    Rental: 'rental',
    Repair: 'repair',
    Registeration: 'registeration',
    Board: 'board'
} as const;

export type ActivityCategoryEnum = typeof ActivityCategoryEnum[keyof typeof ActivityCategoryEnum];


