/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AdminStatistics
 */
export interface AdminStatistics {
    /**
     * 총 사용자 수
     * @type {number}
     * @memberof AdminStatistics
     */
    'total_users': number;
    /**
     * 총 대여소 수
     * @type {number}
     * @memberof AdminStatistics
     */
    'total_stations': number;
    /**
     * 총 자전거 수
     * @type {number}
     * @memberof AdminStatistics
     */
    'total_bikes': number;
    /**
     * 현재 대여 중인 자전거 수
     * @type {number}
     * @memberof AdminStatistics
     */
    'active_rentals': number;
    /**
     * 오늘 대여 건수
     * @type {number}
     * @memberof AdminStatistics
     */
    'today_rentals_today': number;
    /**
     * 오늘 수리 건수
     * @type {number}
     * @memberof AdminStatistics
     */
    'total_repairs_pending': number;
}

