/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AdminStatisticsTimePopulationInnerInner
 */
export interface AdminStatisticsTimePopulationInnerInner {
    /**
     * 0/3/6/9/.../15/18/21
     * @type {number}
     * @memberof AdminStatisticsTimePopulationInnerInner
     */
    'time': number;
    /**
     * 사용 횟수
     * @type {number}
     * @memberof AdminStatisticsTimePopulationInnerInner
     */
    'usage': number;
}

