/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Activity } from './activity';
// May contain unused imports in some cases
// @ts-ignore
import type { AdminStatisticsBikeStatus } from './admin-statistics-bike-status';
// May contain unused imports in some cases
// @ts-ignore
import type { AdminStatisticsPopularStations } from './admin-statistics-popular-stations';
// May contain unused imports in some cases
// @ts-ignore
import type { AdminStatisticsRepairStatus } from './admin-statistics-repair-status';
// May contain unused imports in some cases
// @ts-ignore
import type { AdminStatisticsStationStatus } from './admin-statistics-station-status';
// May contain unused imports in some cases
// @ts-ignore
import type { AdminStatisticsTimePopulationInnerInner } from './admin-statistics-time-population-inner-inner';

/**
 * 
 * @export
 * @interface AdminStatistics
 */
export interface AdminStatistics {
    /**
     * 총 사용자 수
     * @type {number}
     * @memberof AdminStatistics
     */
    'total_users': number;
    /**
     * 총 대여소 수
     * @type {number}
     * @memberof AdminStatistics
     */
    'total_stations': number;
    /**
     * 총 자전거 수
     * @type {number}
     * @memberof AdminStatistics
     */
    'total_bikes': number;
    /**
     * 현재 대여 중인 자전거 수
     * @type {number}
     * @memberof AdminStatistics
     */
    'active_rentals': number;
    /**
     * 오늘 대여 건수
     * @type {number}
     * @memberof AdminStatistics
     */
    'today_rentals_today': number;
    /**
     * 오늘 수리 건수
     * @type {number}
     * @memberof AdminStatistics
     */
    'total_repairs_pending': number;
    /**
     * 최근 활동(회원가입/대여/게시글 작성 등등) (최신순 5개)
     * @type {Array<Activity>}
     * @memberof AdminStatistics
     */
    'recent_activities': Array<Activity>;
    /**
     * 
     * @type {AdminStatisticsBikeStatus}
     * @memberof AdminStatistics
     */
    'bike_status': AdminStatisticsBikeStatus;
    /**
     * 
     * @type {AdminStatisticsStationStatus}
     * @memberof AdminStatistics
     */
    'station_status': AdminStatisticsStationStatus;
    /**
     * 
     * @type {AdminStatisticsRepairStatus}
     * @memberof AdminStatistics
     */
    'repair_status': AdminStatisticsRepairStatus;
    /**
     * 시간대별 대여량(반납 아님)
     * @type {Array<Array<AdminStatisticsTimePopulationInnerInner>>}
     * @memberof AdminStatistics
     */
    'time_population': Array<Array<AdminStatisticsTimePopulationInnerInner>>;
    /**
     * 
     * @type {AdminStatisticsPopularStations}
     * @memberof AdminStatistics
     */
    'popular_stations': AdminStatisticsPopularStations;
}

