/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 자전거 현황
 * @export
 * @interface AdminStatisticsBikeStatus
 */
export interface AdminStatisticsBikeStatus {
    /**
     * 정상
     * @type {number}
     * @memberof AdminStatisticsBikeStatus
     */
    'available': number;
    /**
     * 대여중
     * @type {number}
     * @memberof AdminStatisticsBikeStatus
     */
    'rented': number;
    /**
     * 고장/수리
     * @type {number}
     * @memberof AdminStatisticsBikeStatus
     */
    'maintenence': number;
}

