/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StationUsageCount } from './station-usage-count';

/**
 * 인기있는 정류장 통계
 * @export
 * @interface AdminStatisticsPopularStations
 */
export interface AdminStatisticsPopularStations {
    /**
     * 
     * @type {Array<StationUsageCount>}
     * @memberof AdminStatisticsPopularStations
     */
    'monthly': Array<StationUsageCount>;
    /**
     * 상위 5개
     * @type {Array<StationUsageCount>}
     * @memberof AdminStatisticsPopularStations
     */
    'weekly': Array<StationUsageCount>;
    /**
     * 
     * @type {Array<StationUsageCount>}
     * @memberof AdminStatisticsPopularStations
     */
    'daily': Array<StationUsageCount>;
}

