/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AiCourseGet200ResponsePlacesInner
 */
export interface AiCourseGet200ResponsePlacesInner {
    /**
     * 
     * @type {string}
     * @memberof AiCourseGet200ResponsePlacesInner
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof AiCourseGet200ResponsePlacesInner
     */
    'start_lat'?: number;
    /**
     * 
     * @type {number}
     * @memberof AiCourseGet200ResponsePlacesInner
     */
    'start_lon'?: number;
    /**
     * 
     * @type {number}
     * @memberof AiCourseGet200ResponsePlacesInner
     */
    'end_lat'?: number;
    /**
     * 
     * @type {number}
     * @memberof AiCourseGet200ResponsePlacesInner
     */
    'end_lon'?: number;
}

