/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AiCourseGet200ResponsePlacesInner } from './ai-course-get200-response-places-inner';

/**
 * 
 * @export
 * @interface AiCourseGet200Response
 */
export interface AiCourseGet200Response {
    /**
     * 장소 반환
     * @type {Array<AiCourseGet200ResponsePlacesInner>}
     * @memberof AiCourseGet200Response
     */
    'places': Array<AiCourseGet200ResponsePlacesInner>;
}

