/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Calculate
 */
export interface Calculate {
    /**
     * 출발지 위도
     * @type {number}
     * @memberof Calculate
     */
    'startLat': number;
    /**
     * 출발지 경도
     * @type {number}
     * @memberof Calculate
     */
    'startLon': number;
    /**
     * 목적지 위도
     * @type {number}
     * @memberof Calculate
     */
    'endLat': number;
    /**
     * 목적지 경도
     * @type {number}
     * @memberof Calculate
     */
    'endLon': number;
}

