/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ChangePassword
 */
export interface ChangePassword {
    /**
     * 현재 비밀번호
     * @type {string}
     * @memberof ChangePassword
     */
    'currentPassword': string;
    /**
     * 새 비밀번호 (8자 이상)
     * @type {string}
     * @memberof ChangePassword
     */
    'newPassword': string;
}

