/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Comment
 */
export interface Comment {
    /**
     * 댓글 고유 ID
     * @type {string}
     * @memberof Comment
     */
    'comment_id': string;
    /**
     * 작성자 ID
     * @type {string}
     * @memberof Comment
     */
    'author_id': string;
    /**
     * 작성자 이름
     * @type {string}
     * @memberof Comment
     */
    'author_name': string;
    /**
     * 게시글 카테고리 (notice: 공지, info: 정보, question: 질문, free: 자유)
     * @type {string}
     * @memberof Comment
     */
    'category': CommentCategoryEnum;
    /**
     * 작성 시간
     * @type {string}
     * @memberof Comment
     */
    'created_at': string;
}

export const CommentCategoryEnum = {
    Notice: 'notice',
    Info: 'info',
    Question: 'question',
    Free: 'free'
} as const;

export type CommentCategoryEnum = typeof CommentCategoryEnum[keyof typeof CommentCategoryEnum];


