/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommonMetadata
 */
export interface CommonMetadata {
    /**
     * 응답 생성 시간 (ISO 8601)
     * @type {string}
     * @memberof CommonMetadata
     */
    'timestamp': string;
    /**
     * API 버전
     * @type {string}
     * @memberof CommonMetadata
     */
    'version': string;
    /**
     * API 이름
     * @type {string}
     * @memberof CommonMetadata
     */
    'api'?: string;
    /**
     * 작업 타입
     * @type {string}
     * @memberof CommonMetadata
     */
    'operation'?: string;
    /**
     * 요청 추적을 위한 고유 ID
     * @type {string}
     * @memberof CommonMetadata
     */
    'requestId': string;
    /**
     * 처리 시간 (밀리초)
     * @type {number}
     * @memberof CommonMetadata
     */
    'processingTime'?: number;
}

