/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateStation
 */
export interface CreateStation {
    /**
     * 대여소 이름
     * @type {string}
     * @memberof CreateStation
     */
    'name': string;
    /**
     * 대여소 주소
     * @type {string}
     * @memberof CreateStation
     */
    'address': string;
    /**
     * 위도
     * @type {string}
     * @memberof CreateStation
     */
    'latitude': string;
    /**
     * 경도
     * @type {string}
     * @memberof CreateStation
     */
    'longitude': string;
    /**
     * 최대 수용 대수
     * @type {number}
     * @memberof CreateStation
     */
    'capacity': number;
}

