/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreatePost
 */
export interface CreatePost {
    /**
     * 게시글 제목
     * @type {string}
     * @memberof CreatePost
     */
    'title': string;
    /**
     * 게시글 내용
     * @type {string}
     * @memberof CreatePost
     */
    'content': string;
    /**
     * 게시글 카테고리
     * @type {string}
     * @memberof CreatePost
     */
    'category'?: CreatePostCategoryEnum;
}

export const CreatePostCategoryEnum = {
    Notice: 'notice',
    Info: 'info',
    Question: 'question',
    Free: 'free'
} as const;

export type CreatePostCategoryEnum = typeof CreatePostCategoryEnum[keyof typeof CreatePostCategoryEnum];


