/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Create2
 */
export interface Create2 {
    /**
     * 신고 대상
     * @type {string}
     * @memberof Create2
     */
    'type': Create2TypeEnum;
    /**
     * 자전거 ID (type이 bike일 때 필수)
     * @type {string}
     * @memberof Create2
     */
    'bikeId'?: string;
    /**
     * 대여소 ID (type이 station일 때 필수)
     * @type {string}
     * @memberof Create2
     */
    'stationId'?: string;
    /**
     * 고장 카테고리
     * @type {string}
     * @memberof Create2
     */
    'category': Create2CategoryEnum;
    /**
     * 고장 상세 설명
     * @type {string}
     * @memberof Create2
     */
    'description': string;
    /**
     * 첨부 사진 URL 목록
     * @type {Array<string>}
     * @memberof Create2
     */
    'photos'?: Array<string>;
}

export const Create2TypeEnum = {
    Bike: 'bike',
    Station: 'station'
} as const;

export type Create2TypeEnum = typeof Create2TypeEnum[keyof typeof Create2TypeEnum];
export const Create2CategoryEnum = {
    Brake: 'brake',
    Tire: 'tire',
    Chain: 'chain',
    Light: 'light',
    Seat: 'seat',
    Bell: 'bell',
    Other: 'other'
} as const;

export type Create2CategoryEnum = typeof Create2CategoryEnum[keyof typeof Create2CategoryEnum];


