/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DataRentalCreateSummary
 */
export interface DataRentalCreateSummary {
    /**
     * 시작 역 이름
     * @type {string}
     * @memberof DataRentalCreateSummary
     */
    'start_station_name': string;
    /**
     * 시작 역 주소
     * @type {string}
     * @memberof DataRentalCreateSummary
     */
    'start_station_address': string;
}

