/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DataStationsStatusListInner
 */
export interface DataStationsStatusListInner {
    /**
     * 
     * @type {string}
     * @memberof DataStationsStatusListInner
     */
    'id': string;
    /**
     * 
     * @type {number}
     * @memberof DataStationsStatusListInner
     */
    'bike_count': number;
    /**
     * 
     * @type {string}
     * @memberof DataStationsStatusListInner
     */
    'status': DataStationsStatusListInnerStatusEnum;
}

export const DataStationsStatusListInnerStatusEnum = {
    Active: 'active',
    Inactive: 'inactive'
} as const;

export type DataStationsStatusListInnerStatusEnum = typeof DataStationsStatusListInnerStatusEnum[keyof typeof DataStationsStatusListInnerStatusEnum];


