/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EntityPost
 */
export interface EntityPost {
    /**
     * 게시글 고유 ID
     * @type {string}
     * @memberof EntityPost
     */
    'id': string;
    /**
     * 게시글 카테고리 (notice: 공지, info: 정보, question: 질문, free: 자유)
     * @type {string}
     * @memberof EntityPost
     */
    'category': EntityPostCategoryEnum;
    /**
     * 게시글 제목
     * @type {string}
     * @memberof EntityPost
     */
    'title': string;
    /**
     * 게시글 내용
     * @type {string}
     * @memberof EntityPost
     */
    'content': string;
    /**
     * 작성자 이름
     * @type {string}
     * @memberof EntityPost
     */
    'author': string;
    /**
     * 작성자 ID
     * @type {string}
     * @memberof EntityPost
     */
    'authorId': string;
    /**
     * 조회수
     * @type {number}
     * @memberof EntityPost
     */
    'views': number;
    /**
     * 좋아요 수
     * @type {number}
     * @memberof EntityPost
     */
    'likes': number;
    /**
     * 댓글 수
     * @type {number}
     * @memberof EntityPost
     */
    'comments': number;
    /**
     * 작성 시간
     * @type {string}
     * @memberof EntityPost
     */
    'createdAt': string;
    /**
     * 공지사항 고정 여부
     * @type {boolean}
     * @memberof EntityPost
     */
    'isPinned'?: boolean;
}

export const EntityPostCategoryEnum = {
    Notice: 'notice',
    Info: 'info',
    Question: 'question',
    Free: 'free'
} as const;

export type EntityPostCategoryEnum = typeof EntityPostCategoryEnum[keyof typeof EntityPostCategoryEnum];


