/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EntityStation } from './entity-station';

/**
 * 
 * @export
 * @interface EntityRouteInfo
 */
export interface EntityRouteInfo {
    /**
     * 
     * @type {EntityStation}
     * @memberof EntityRouteInfo
     */
    'startStation': EntityStation;
    /**
     * 
     * @type {EntityStation}
     * @memberof EntityRouteInfo
     */
    'endStation': EntityStation;
    /**
     * 자전거 이동 거리 (km)
     * @type {number}
     * @memberof EntityRouteInfo
     */
    'distance': number;
    /**
     * 예상 소요 시간 (분)
     * @type {number}
     * @memberof EntityRouteInfo
     */
    'duration': number;
    /**
     * 출발지에서 출발 대여소까지 도보 거리 (km)
     * @type {number}
     * @memberof EntityRouteInfo
     */
    'walkingDistanceToStart': number;
    /**
     * 도착 대여소에서 목적지까지 도보 거리 (km)
     * @type {number}
     * @memberof EntityRouteInfo
     */
    'walkingDistanceFromEnd': number;
}

