/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EntityCourseInfo
 */
export interface EntityCourseInfo {
    /**
     * 코스 이름
     * @type {string}
     * @memberof EntityCourseInfo
     */
    'name': string;
    /**
     * 코스 설명
     * @type {string}
     * @memberof EntityCourseInfo
     */
    'description': string;
    /**
     * 예상 소요 시간 (분)
     * @type {number}
     * @memberof EntityCourseInfo
     */
    'duration': number;
    /**
     * 예상 칼로리 소모량 (kcal)
     * @type {number}
     * @memberof EntityCourseInfo
     */
    'calories': number;
    /**
     * 난이도
     * @type {string}
     * @memberof EntityCourseInfo
     */
    'difficulty': EntityCourseInfoDifficultyEnum;
    /**
     * 총 거리 (km)
     * @type {number}
     * @memberof EntityCourseInfo
     */
    'distance': number;
    /**
     * 코스 주요 특징
     * @type {Array<string>}
     * @memberof EntityCourseInfo
     */
    'highlights': Array<string>;
}

export const EntityCourseInfoDifficultyEnum = {
    : '최하',
    2: '하',
    3: '중',
    4: '상',
    5: '최상'
} as const;

export type EntityCourseInfoDifficultyEnum = typeof EntityCourseInfoDifficultyEnum[keyof typeof EntityCourseInfoDifficultyEnum];


