/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ErrorError
 */
export interface ErrorError {
    /**
     * 에러 코드
     * @type {string}
     * @memberof ErrorError
     */
    'code': string;
    /**
     * 에러 메시지
     * @type {string}
     * @memberof ErrorError
     */
    'message': string;
    /**
     * 추가 에러 정보
     * @type {object}
     * @memberof ErrorError
     */
    'details'?: object;
}

