/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EntityStation } from './entity-station';

/**
 * 
 * @export
 * @interface GetAllStations200ResponseAllOfData
 */
export interface GetAllStations200ResponseAllOfData {
    /**
     * 
     * @type {Array<EntityStation>}
     * @memberof GetAllStations200ResponseAllOfData
     */
    'stations': Array<EntityStation>;
    /**
     * 
     * @type {number}
     * @memberof GetAllStations200ResponseAllOfData
     */
    'total': number;
}

