/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetBikeAdmin200ResponseAllOfData } from './get-bike-admin200-response-all-of-data';
// May contain unused imports in some cases
// @ts-ignore
import type { Success } from './success';

/**
 * @type GetBikeAdmin200Response
 * @export
 */
export type GetBikeAdmin200Response = Success;


