/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Comment } from './comment';

/**
 * 
 * @export
 * @interface Post
 */
export interface Post {
    /**
     * 게시글 고유 ID
     * @type {string}
     * @memberof Post
     */
    'id': string;
    /**
     * 작성자 ID
     * @type {string}
     * @memberof Post
     */
    'author_id': string;
    /**
     * 작성자 이름
     * @type {string}
     * @memberof Post
     */
    'author_name': string;
    /**
     * 게시글 카테고리 (notice: 공지, info: 정보, question: 질문, free: 자유)
     * @type {string}
     * @memberof Post
     */
    'category': PostCategoryEnum;
    /**
     * 게시글 제목
     * @type {string}
     * @memberof Post
     */
    'title': string;
    /**
     * 게시글 내용
     * @type {string}
     * @memberof Post
     */
    'content': string;
    /**
     * 조회수
     * @type {number}
     * @memberof Post
     */
    'views': number;
    /**
     * 댓글 수
     * @type {number}
     * @memberof Post
     */
    'comment_count': number;
    /**
     * 공지사항 고정 여부
     * @type {number}
     * @memberof Post
     */
    'is_pinned'?: number;
    /**
     * 작성 시간
     * @type {string}
     * @memberof Post
     */
    'created_at': string;
    /**
     * 수정 시간
     * @type {string}
     * @memberof Post
     */
    'updated_at': string;
    /**
     * 
     * @type {Array<Comment>}
     * @memberof Post
     */
    'comments': Array<Comment>;
}

export const PostCategoryEnum = {
    Notice: 'notice',
    Info: 'info',
    Question: 'question',
    Free: 'free'
} as const;

export type PostCategoryEnum = typeof PostCategoryEnum[keyof typeof PostCategoryEnum];


