/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RecommendCoursePreferences } from './recommend-course-preferences';

/**
 * 
 * @export
 * @interface RecommendCourse
 */
export interface RecommendCourse {
    /**
     * 자연어 코스 추천 요청
     * @type {string}
     * @memberof RecommendCourse
     */
    'prompt': string;
    /**
     * 
     * @type {RecommendCoursePreferences}
     * @memberof RecommendCourse
     */
    'preferences'?: RecommendCoursePreferences;
}

