/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RecommendCoursePreferences
 */
export interface RecommendCoursePreferences {
    /**
     * 희망 난이도
     * @type {string}
     * @memberof RecommendCoursePreferences
     */
    'difficulty'?: RecommendCoursePreferencesDifficultyEnum;
    /**
     * 희망 소요 시간 (분)
     * @type {number}
     * @memberof RecommendCoursePreferences
     */
    'duration'?: number;
    /**
     * 희망 거리 (km)
     * @type {number}
     * @memberof RecommendCoursePreferences
     */
    'distance'?: number;
}

export const RecommendCoursePreferencesDifficultyEnum = {
    : '최하',
    2: '하',
    3: '중',
    4: '상',
    5: '최상'
} as const;

export type RecommendCoursePreferencesDifficultyEnum = typeof RecommendCoursePreferencesDifficultyEnum[keyof typeof RecommendCoursePreferencesDifficultyEnum];


