/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RentalReturnSummary
 */
export interface RentalReturnSummary {
    /**
     * 
     * @type {string}
     * @memberof RentalReturnSummary
     */
    'startStation': string;
    /**
     * 
     * @type {string}
     * @memberof RentalReturnSummary
     */
    'endStation': string;
    /**
     * 이용 시간 (분)
     * @type {number}
     * @memberof RentalReturnSummary
     */
    'duration': number;
    /**
     * 이동 거리 (km)
     * @type {number}
     * @memberof RentalReturnSummary
     */
    'distance': number;
}

