/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Rental
 */
export interface Rental {
    /**
     * 대여 고유 ID
     * @type {string}
     * @memberof Rental
     */
    'id': string;
    /**
     * 사용자 ID
     * @type {string}
     * @memberof Rental
     */
    'user_id': string;
    /**
     * 자전거 ID (Seoul Public Bike)
     * @type {string}
     * @memberof Rental
     */
    'bike_id': string;
    /**
     * 출발 대여소 ID
     * @type {string}
     * @memberof Rental
     */
    'start_station_id': string;
    /**
     * 도착 대여소 ID (반납 시에만)
     * @type {string}
     * @memberof Rental
     */
    'end_station_id': string | null;
    /**
     * 대여 시작 시간
     * @type {string}
     * @memberof Rental
     */
    'rental_time': string | null;
    /**
     * 반납 시간
     * @type {string}
     * @memberof Rental
     */
    'return_time': string | null;
    /**
     * 이용 시간 (분 단위)
     * @type {number}
     * @memberof Rental
     */
    'duration'?: number | null;
    /**
     * 이동 거리 (km)
     * @type {string}
     * @memberof Rental
     */
    'distance'?: string | null;
    /**
     * 대여 상태 (rented: 대여 중, returned: 반납 완료)
     * @type {string}
     * @memberof Rental
     */
    'status': RentalStatusEnum;
}

export const RentalStatusEnum = {
    Rented: 'rented',
    Returned: 'returned'
} as const;

export type RentalStatusEnum = typeof RentalStatusEnum[keyof typeof RentalStatusEnum];


