/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Rental } from './rental';
// May contain unused imports in some cases
// @ts-ignore
import type { RentalReturnSummary } from './rental-return-summary';

/**
 * 
 * @export
 * @interface RentalReturn
 */
export interface RentalReturn {
    /**
     * 
     * @type {Rental}
     * @memberof RentalReturn
     */
    'rental': Rental;
    /**
     * 
     * @type {RentalReturnSummary}
     * @memberof RentalReturn
     */
    'summary': RentalReturnSummary;
}

