/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Repair1
 */
export interface Repair1 {
    /**
     * 신고 고유 ID
     * @type {string}
     * @memberof Repair1
     */
    'id': string;
    /**
     * 신고 대상 (bike: 자전거, station: 대여소)
     * @type {string}
     * @memberof Repair1
     */
    'type': Repair1TypeEnum;
    /**
     * 자전거 ID (type이 bike일 때만)
     * @type {string}
     * @memberof Repair1
     */
    'bikeId'?: string;
    /**
     * 대여소 ID (type이 station일 때만)
     * @type {string}
     * @memberof Repair1
     */
    'stationId'?: string;
    /**
     * 고장 카테고리
     * @type {string}
     * @memberof Repair1
     */
    'category': Repair1CategoryEnum;
    /**
     * 고장 상세 설명
     * @type {string}
     * @memberof Repair1
     */
    'description': string;
    /**
     * 신고자 이름
     * @type {string}
     * @memberof Repair1
     */
    'reporter': string;
    /**
     * 신고자 ID
     * @type {string}
     * @memberof Repair1
     */
    'reporterId': string;
    /**
     * 처리 상태 (pending: 대기 중, in-progress: 처리 중, completed: 완료)
     * @type {string}
     * @memberof Repair1
     */
    'status': Repair1StatusEnum;
    /**
     * 신고 접수 시간
     * @type {string}
     * @memberof Repair1
     */
    'createdAt': string;
    /**
     * 처리 완료 시간
     * @type {string}
     * @memberof Repair1
     */
    'completedAt'?: string;
    /**
     * 관리자 메모
     * @type {string}
     * @memberof Repair1
     */
    'adminNote'?: string;
}

export const Repair1TypeEnum = {
    Bike: 'bike',
    Station: 'station'
} as const;

export type Repair1TypeEnum = typeof Repair1TypeEnum[keyof typeof Repair1TypeEnum];
export const Repair1CategoryEnum = {
    Brake: 'brake',
    Tire: 'tire',
    Chain: 'chain',
    Light: 'light',
    Seat: 'seat',
    Bell: 'bell',
    Other: 'other'
} as const;

export type Repair1CategoryEnum = typeof Repair1CategoryEnum[keyof typeof Repair1CategoryEnum];
export const Repair1StatusEnum = {
    Pending: 'pending',
    InProgress: 'in-progress',
    Completed: 'completed'
} as const;

export type Repair1StatusEnum = typeof Repair1StatusEnum[keyof typeof Repair1StatusEnum];


