/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { User1 } from './user1';

/**
 * 
 * @export
 * @interface Signup1
 */
export interface Signup1 {
    /**
     * 
     * @type {User1}
     * @memberof Signup1
     */
    'user': User1;
    /**
     * JWT 인증 토큰
     * @type {string}
     * @memberof Signup1
     */
    'token': string;
}

