/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Signup
 */
export interface Signup {
    /**
     * 이메일 주소
     * @type {string}
     * @memberof Signup
     */
    'email': string;
    /**
     * 비밀번호 (8자 이상)
     * @type {string}
     * @memberof Signup
     */
    'password': string;
    /**
     * 이름
     * @type {string}
     * @memberof Signup
     */
    'name': string;
    /**
     * 전화번호 (형식: 010-XXXX-XXXX)
     * @type {string}
     * @memberof Signup
     */
    'phone': string;
}

