/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface StationUsageCount
 */
export interface StationUsageCount {
    /**
     * 정류소 이름
     * @type {string}
     * @memberof StationUsageCount
     */
    'name': string;
    /**
     * 정류소 ID
     * @type {string}
     * @memberof StationUsageCount
     */
    'id': string;
    /**
     * 사용횟수(대여 or 반납)
     * @type {number}
     * @memberof StationUsageCount
     */
    'count': number;
}

