/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Success
 */
export interface Success {
    /**
     * 응답 상태
     * @type {string}
     * @memberof Success
     */
    'status': SuccessStatusEnum;
    /**
     * 응답 데이터 (구체적인 타입은 각 엔드포인트별로 정의됨)
     * @type {object}
     * @memberof Success
     */
    'data': object;
}

export const SuccessStatusEnum = {
    Success: 'success'
} as const;

export type SuccessStatusEnum = typeof SuccessStatusEnum[keyof typeof SuccessStatusEnum];


