/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateStation
 */
export interface UpdateStation {
    /**
     * 대여소 이름
     * @type {string}
     * @memberof UpdateStation
     */
    'name'?: string;
    /**
     * 대여소 주소
     * @type {string}
     * @memberof UpdateStation
     */
    'address'?: string;
    /**
     * 자전거 최대 수용량
     * @type {number}
     * @memberof UpdateStation
     */
    'capacity'?: number;
    /**
     * 운영 상태
     * @type {string}
     * @memberof UpdateStation
     */
    'status'?: UpdateStationStatusEnum;
}

export const UpdateStationStatusEnum = {
    Active: 'active',
    Inactive: 'inactive'
} as const;

export type UpdateStationStatusEnum = typeof UpdateStationStatusEnum[keyof typeof UpdateStationStatusEnum];


