/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateUserStatus
 */
export interface UpdateUserStatus {
    /**
     * 사용자 상태
     * @type {string}
     * @memberof UpdateUserStatus
     */
    'status': UpdateUserStatusStatusEnum;
}

export const UpdateUserStatusStatusEnum = {
    Active: 'active',
    Blocked: 'blocked'
} as const;

export type UpdateUserStatusStatusEnum = typeof UpdateUserStatusStatusEnum[keyof typeof UpdateUserStatusStatusEnum];


