/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface User1
 */
export interface User1 {
    /**
     * 사용자 고유 ID
     * @type {string}
     * @memberof User1
     */
    'id': string;
    /**
     * 사용자 이메일 주소 (로그인 ID)
     * @type {string}
     * @memberof User1
     */
    'email': string;
    /**
     * 사용자 이름
     * @type {string}
     * @memberof User1
     */
    'name': string;
    /**
     * 사용자 역할 (user: 일반 사용자, admin: 관리자)
     * @type {string}
     * @memberof User1
     */
    'role': User1RoleEnum;
}

export const User1RoleEnum = {
    User: 'user',
    Admin: 'admin'
} as const;

export type User1RoleEnum = typeof User1RoleEnum[keyof typeof User1RoleEnum];


