/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StationUsageCount } from './station-usage-count';

/**
 * 
 * @export
 * @interface UserStatistics
 */
export interface UserStatistics {
    /**
     * 총 대여 횟수
     * @type {number}
     * @memberof UserStatistics
     */
    'totalRentals': number;
    /**
     * 총 이동 거리 (km)
     * @type {number}
     * @memberof UserStatistics
     */
    'totalDistance': number;
    /**
     * 총 이용 시간 (분)
     * @type {number}
     * @memberof UserStatistics
     */
    'totalDuration': number;
    /**
     * 평균 이동 거리 (km)
     * @type {number}
     * @memberof UserStatistics
     */
    'averageDistance': number;
    /**
     * 평균 이용 시간 (분)
     * @type {number}
     * @memberof UserStatistics
     */
    'averageDuration': number;
    /**
     * 월별 사용시간
     * @type {Array<number>}
     * @memberof UserStatistics
     */
    'monthly_usage': Array<number>;
    /**
     * 요일번 사용시간
     * @type {Array<number>}
     * @memberof UserStatistics
     */
    'weekly_usage': Array<number>;
    /**
     * 대여 or 반납 자주 하는 정류장
     * @type {Array<StationUsageCount>}
     * @memberof UserStatistics
     */
    'commonly_used_station': Array<StationUsageCount>;
}

