/* tslint:disable */
/* eslint-disable */
/**
 * 서울 따릉이 시뮬레이션 플랫폼 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 사용자 고유 ID
     * @type {string}
     * @memberof User
     */
    'id': string;
    /**
     * 현재 자전거 이용중인지
     * @type {boolean}
     * @memberof User
     */
    'is_renting': boolean;
    /**
     * 사용자 이메일 주소 (로그인 ID)
     * @type {string}
     * @memberof User
     */
    'email': string;
    /**
     * 사용자 이름
     * @type {string}
     * @memberof User
     */
    'name': string;
    /**
     * 사용자 역할 (user: 일반 사용자, admin: 관리자)
     * @type {string}
     * @memberof User
     */
    'role': UserRoleEnum;
    /**
     * 전화번호 (형식: 010-XXXX-XXXX)
     * @type {string}
     * @memberof User
     */
    'phone': string;
    /**
     * 상태
     * @type {string}
     * @memberof User
     */
    'status': string;
}

export const UserRoleEnum = {
    User: 'user',
    Admin: 'admin'
} as const;

export type UserRoleEnum = typeof UserRoleEnum[keyof typeof UserRoleEnum];


